[monitor:///tmp/sample-data/lab02_account_creation.json]
disabled = false
index = lab02
sourcetype = WinEventLog:Security
host = CORP-DC01

[monitor:///tmp/sample-data/lab03_fin7_security.json]
disabled = false
index = lab03
sourcetype = WinEventLog:Security
host = CORP-WS01

[monitor:///tmp/sample-data/lab03_fin7_sysmon.json]
disabled = false
index = lab03
sourcetype = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
host = CORP-WS01

[http]
disabled = false
port = 8088
token = immersivelabs-hec-token
